### PR TITLE
UI update

### PR DESCRIPTION
**Pull request by akashjss**
Update UI and add option to select themes.
Submit user request by pressing enter.

### CODE REVIEW

**Comment by AmberSahdev** [comment]
Thanks for the PR @akashjss, @akash-gupta-parloa! 
I was unaware of this library but it seems to have a lot of potential. 

Before I merge are you seeing the same UI artifact on your end where on the default theme (superhero) it shows the dropdown menus as too large? Doesn't seem to happen with other themes. 
Would you happen to have an idea as to why it's happening if you've seen it before? 

Attaching screenshot for reference 

Superhero: (buggy)
MacOS
Screenshot 2024-11-09 at 11 14 42 PM


Solar: 
Screenshot 2024-11-09 at 11 18 26 PM

**Comment by AmberSahdev** [comment]
Also do you know of an easy way to maintain the default dark theme that was there before with tkinter?

**Comment by akashjss** [comment]
@AmberSahdev the theme selection box size should be fixed now.
For the themes It would not be a straight forward change :)

**Review by AmberSahdev — APPROVED** [review]

**Comment by AmberSahdev** [comment]
Thank you for the enhancements, @akashjss! Merged.

**Pull request merged**
